### ISSUE TITLE
Didn't handle error friendly

### ISSUE THREAD

**Issue by LongTengDao** [acornjs/acorn-private-class-elements#9]
TEST.js:

```js
'use strict';
Error.stackTraceLimit = 100;
const Parser = require('acorn').Parser.extend(require('acorn-class-fields'));
Parser.parse('a.#1=c;');
```

The error thrown is not friendly with `loc` info any more:

```
        if (!this._privateBoundNamesStack.length || !this._privateBoundNamesStack[this._privateBoundNamesStack.length - 1][node.property.name]) {
                                          ^
TypeError: Cannot read property 'length' of undefined
    at Object.parseSubscript             (/node_modules/acorn-class-fields/node_modules/acorn-private-class-elements/index.js:101:43)
    at Object.pp$3.parseSubscripts       (/node_modules/acorn/dist/acorn.js:2104:26)
    at Object.pp$3.parseExprSubscripts   (/node_modules/acorn/dist/acorn.js:2092:23)
    at Object.pp$3.parseMaybeUnary       (/node_modules/acorn/dist/acorn.js:2066:19)
    at Object.parseMaybeUnary            (/node_modules/acorn-class-fields/node_modules/acorn-private-class-elements/index.js:112:29)
    at Object.pp$3.parseExprOps          (/node_modules/acorn/dist/acorn.js:2010:21)
    at Object.pp$3.parseMaybeConditional (/node_modules/acorn/dist/acorn.js:1993:21)
    at Object.pp$3.parseMaybeAssign      (/node_modules/acorn/dist/acorn.js:1968:21)
    at Object.pp$3.parseExpression       (/node_modules/acorn/dist/acorn.js:1933:21)
    at Object.pp$1.parseStatement        (/node_modules/acorn/dist/acorn.js:877:47)
    at Object.pp$1.parseTopLevel         (/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse                      (/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse                    (/node_modules/acorn/dist/acorn.js:576:37)
    at Object.<anonymous>                (/TEST.js:4:8)
    at Module._compile                   (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js     (internal/modules/cjs/loader.js:991:10)
    at Module.load                       (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load             (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain           (internal/modules/cjs/loader.js:1043:10)
    at                                   (internal/main/run_main_module.js:17:11)
```

**Comment by adrianheine** [comment]
This now throws a `SyntaxError: Usage of undeclared private name`, I think that's alright.
